name: Build Python Executables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - os: ubuntu-22.04
            target: linux
            shell: bash
          - os: windows-latest
            target: windows
            shell: powershell
          - os: macos-latest
            target: macos
            shell: bash

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller main.py --onefile --name postmaker-${{ matrix.target }}

      - name: Create bin directory
        run: |
          mkdir -p bin

      - name: Move built file to bin directory
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            move dist\\postmaker-${{ matrix.target }}.exe bin\\
          else
            mv dist/postmaker-${{ matrix.target }} bin/
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: postmaker-${{ matrix.target }}
          path: |
            bin/postmaker-${{ matrix.target }}*
